#!/usr/bin/env python

import sys, re

file = sys.argv[1]
#file = test.qdh

class QDHInterpreter:
    def __init__(self):
        self.code = self.readfile()
        self.vars = {}
        self.stack = []
        self.pc = 0

    def readfile(self):
        try:
            with open(file, 'r') as f:
                return f.read()
        except FileNotFoundError:
            print(f"File {file} not found")
            sys.exit(1)

    def run(self):
        lines = self.code.split('\n')
        while self.pc < len(lines):
            line = lines[self.pc].lstrip()
            if line.startswith("if"):
                if self.eval_expr(line[3:-1]) == "true":
                    self.pc += 1
                else:
                    while not line.startswith("}"):
                        self.pc += 1
                        line = lines[self.pc].lstrip()
                    self.pc += 1
            elif line.startswith("while"):
                pass
            elif "=" in line:
                var, expr = line.split(" = ")
                self.vars[var] = self.eval_expr(expr)
                self.pc += 1
            elif line.startswith("print"):
                if line[6] == '"':
                    print(line[7:-2])
                else:
                    print(self.eval_expr(line[6:-1]))
                self.pc += 1
            else:
                self.pc += 1

    def eval_expr(self, expr):
        tokens = self.tokenize(expr)
        postfix = self.infix_to_postfix(tokens)
        return self.eval_postfix(postfix)

    def tokenize(self, expr):
        token_pattern = r'[a-zA-Z_][a-zA-Z_0-9]*|\d+|true|false|[+\-*/<>=!()^]+'
        return re.findall(token_pattern, expr)

    def infix_to_postfix(self, tokens):
        precedence = {'<=':1, '<':1, '>=':1, '>':1, '==':1, '+':1, '-':1, '*':2, '/':2, '^':3}
        postfix = []
        operators = []
        for token in tokens:
            if token.isdigit() or token in ['true', 'false']:
                postfix.append(token)
            elif token in self.vars:
                postfix.append(self.vars[token])
            elif token in precedence:
                while operators and operators[-1] != '(' and precedence[token] <= precedence[operators[-1]]:
                    postfix.append(operators.pop())
                else:
                    operators.append(token)
            elif token == '(':
                operators.append(token)
            elif token == ')':
                while operators[-1] != '(':
                    postfix.append(operators.pop())
                operators.pop()
        while operators:
            postfix.append(operators.pop())
        return postfix

    def eval_postfix(self, postfix):
        for token in postfix:
            if isinstance(token, int) or isinstance(token, float) or token in ['true', 'false']:
                self.stack.append(token)
            elif token.isdigit():
                self.stack.append(int(token))
            elif token in self.vars:
                self.stack.append(self.vars[token])
            elif token in "+-*/^":
                right = self.stack.pop()
                left = self.stack.pop()
                if token == '+':
                    self.stack.append(left + right)
                elif token == '-':
                    self.stack.append(left - right)
                elif token == '*':
                    self.stack.append(left * right)
                elif token == '/':
                    self.stack.append(left / right)
                elif token == '^':
                    self.stack.append(left ** right)
            elif token in ['<=', '<', '>=', '>', '==']:
                right = self.stack.pop()
                left = self.stack.pop()
                if token == '<=':
                    self.stack.append(str(left <= right).lower())
                elif token == '<':
                    self.stack.append(str(left < right).lower())
                elif token == '>=':
                    self.stack.append(str(left >= right).lower())
                elif token == '>':
                    self.stack.append(str(left > right).lower())
                elif token == '==':
                    self.stack.append(str(left == right).lower())
        return self.stack.pop()

interpreter = QDHInterpreter()
interpreter.run()